name: flutter_store
description: flutter_stores is simple state management for Flutter inspired by Flutter itself. It is clean and simple state management solution without any boilerplate.
version: 1.0.0+2
author: Slava Olenin <umenokin@gmail.com>
homepage: https://github.com/Umenokin/flutter_store

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
